#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : slang
Version  : 2.2.4
Release  : 19
URL      : ftp://space.mit.edu/pub/davis/slang/v2.2/slang-2.2.4.tar.gz
Source0  : ftp://space.mit.edu/pub/davis/slang/v2.2/slang-2.2.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: slang-bin
Requires: slang-lib
Requires: slang-doc
Requires: slang-data
BuildRequires : glibc-utils
BuildRequires : libpng-dev
BuildRequires : ncurses-dev
BuildRequires : onig-dev
BuildRequires : pcre-dev
BuildRequires : zlib-dev
Patch1: stateless.patch

%description
New features and upgrade information for version 2 are described in
the appendices of doc/text/slang.txt and doc/text/cslang.txt.  If you
upgrading from version 1, then you should read these appendices.

%package bin
Summary: bin components for the slang package.
Group: Binaries
Requires: slang-data

%description bin
bin components for the slang package.


%package data
Summary: data components for the slang package.
Group: Data

%description data
data components for the slang package.


%package dev
Summary: dev components for the slang package.
Group: Development
Requires: slang-lib
Requires: slang-bin
Requires: slang-data

%description dev
dev components for the slang package.


%package doc
Summary: doc components for the slang package.
Group: Documentation

%description doc
doc components for the slang package.


%package lib
Summary: lib components for the slang package.
Group: Libraries
Requires: slang-data

%description lib
lib components for the slang package.


%prep
%setup -q -n slang-2.2.4
%patch1 -p1

%build
%configure --disable-static
make V=1  %{?_smp_mflags} -j1

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
make runtests

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/slang/v2/modules/csv-module.so
/usr/lib64/slang/v2/modules/fcntl-module.so
/usr/lib64/slang/v2/modules/fork-module.so
/usr/lib64/slang/v2/modules/iconv-module.so
/usr/lib64/slang/v2/modules/onig-module.so
/usr/lib64/slang/v2/modules/pcre-module.so
/usr/lib64/slang/v2/modules/png-module.so
/usr/lib64/slang/v2/modules/rand-module.so
/usr/lib64/slang/v2/modules/select-module.so
/usr/lib64/slang/v2/modules/slsmg-module.so
/usr/lib64/slang/v2/modules/socket-module.so
/usr/lib64/slang/v2/modules/sysconf-module.so
/usr/lib64/slang/v2/modules/termios-module.so
/usr/lib64/slang/v2/modules/varray-module.so
/usr/lib64/slang/v2/modules/zlib-module.so

%files bin
%defattr(-,root,root,-)
/usr/bin/slsh

%files data
%defattr(-,root,root,-)
/usr/share/doc/slsh/html/slshfun-1.html
/usr/share/doc/slsh/html/slshfun-2.html
/usr/share/doc/slsh/html/slshfun-3.html
/usr/share/doc/slsh/html/slshfun-4.html
/usr/share/doc/slsh/html/slshfun-5.html
/usr/share/doc/slsh/html/slshfun-6.html
/usr/share/doc/slsh/html/slshfun-7.html
/usr/share/doc/slsh/html/slshfun-8.html
/usr/share/doc/slsh/html/slshfun-9.html
/usr/share/doc/slsh/html/slshfun.html
/usr/share/slsh/arrayfuns.sl
/usr/share/slsh/autoload.sl
/usr/share/slsh/cmaps/cool.map
/usr/share/slsh/cmaps/coolwarm.map
/usr/share/slsh/cmaps/copper.map
/usr/share/slsh/cmaps/drywet.map
/usr/share/slsh/cmaps/ds9b.map
/usr/share/slsh/cmaps/ds9sls.map
/usr/share/slsh/cmaps/gebco.map
/usr/share/slsh/cmaps/globe.map
/usr/share/slsh/cmaps/gray.map
/usr/share/slsh/cmaps/haxby.map
/usr/share/slsh/cmaps/hot.map
/usr/share/slsh/cmaps/jet.map
/usr/share/slsh/cmaps/no_green.map
/usr/share/slsh/cmaps/ocean.map
/usr/share/slsh/cmaps/polar.map
/usr/share/slsh/cmaps/rainbow.map
/usr/share/slsh/cmaps/red2green.map
/usr/share/slsh/cmaps/relief.map
/usr/share/slsh/cmaps/sealand.map
/usr/share/slsh/cmaps/seis.map
/usr/share/slsh/cmaps/split.map
/usr/share/slsh/cmaps/topo.map
/usr/share/slsh/cmaps/wysiwyg.map
/usr/share/slsh/cmdopt.sl
/usr/share/slsh/csv.sl
/usr/share/slsh/fcntl.sl
/usr/share/slsh/fork.sl
/usr/share/slsh/glob.sl
/usr/share/slsh/help/arrayfuns.hlp
/usr/share/slsh/help/cmdopt.hlp
/usr/share/slsh/help/csvfuns.hlp
/usr/share/slsh/help/forkfuns.hlp
/usr/share/slsh/help/glob.hlp
/usr/share/slsh/help/onigfuns.hlp
/usr/share/slsh/help/pcrefuns.hlp
/usr/share/slsh/help/pngfuns.hlp
/usr/share/slsh/help/print.hlp
/usr/share/slsh/help/process.hlp
/usr/share/slsh/help/profile.hlp
/usr/share/slsh/help/randfuns.hlp
/usr/share/slsh/help/readascii.hlp
/usr/share/slsh/help/require.hlp
/usr/share/slsh/help/setfuns.hlp
/usr/share/slsh/help/slsmg.hlp
/usr/share/slsh/help/sockfuns.hlp
/usr/share/slsh/help/structfuns.hlp
/usr/share/slsh/iconv.sl
/usr/share/slsh/onig.sl
/usr/share/slsh/pcre.sl
/usr/share/slsh/png.sl
/usr/share/slsh/print.sl
/usr/share/slsh/process.sl
/usr/share/slsh/profile.sl
/usr/share/slsh/rand.sl
/usr/share/slsh/readascii.sl
/usr/share/slsh/require.sl
/usr/share/slsh/rline/complete.sl
/usr/share/slsh/rline/editfuns.sl
/usr/share/slsh/rline/editor.sl
/usr/share/slsh/rline/emacskeys.sl
/usr/share/slsh/rline/history.sl
/usr/share/slsh/rline/histsrch.sl
/usr/share/slsh/rline/slrline.rc
/usr/share/slsh/rline/vikeys.sl
/usr/share/slsh/scripts/jpegsize
/usr/share/slsh/scripts/lsrpm
/usr/share/slsh/scripts/sldb
/usr/share/slsh/scripts/slprof
/usr/share/slsh/scripts/slstkchk
/usr/share/slsh/scripts/svnsh
/usr/share/slsh/select.sl
/usr/share/slsh/setfuns.sl
/usr/share/slsh/sldb.sl
/usr/share/slsh/sldbcore.sl
/usr/share/slsh/sldbsock.sl
/usr/share/slsh/slsh.rc
/usr/share/slsh/slshhelp.sl
/usr/share/slsh/slshrl.sl
/usr/share/slsh/slsmg.sl
/usr/share/slsh/socket.sl
/usr/share/slsh/stkcheck.sl
/usr/share/slsh/structfuns.sl
/usr/share/slsh/sysconf.sl
/usr/share/slsh/termios.sl
/usr/share/slsh/varray.sl
/usr/share/slsh/zlib.sl

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/slang/*
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
